In [27]:
import os
import numpy as np
from PIL import Image
import json


location = "/Users/marcus/Desktop/Training_Data_SVM_Control/"


imageList = []
labelList = []
ytrain = []

for dirName, x, fileList in os.walk(location):
    
    for filename in fileList:
        if(filename[-4:] == ".jpg" and not filename[-7:] == "ged.jpg"):
            
            json_file_location = os.path.join(dirName, filename[:-4] + ".json")
            
            if os.path.exists(json_file_location):
                
                jpg_file_location = os.path.join(dirName, filename)
                imageList.append(str(jpg_file_location))
                labelList.append(str(json_file_location))

for json_file in labelList:
    file = open(json_file)
    data = json.load(file)
    ytrain.append(data["Pano_Data"][0]["label_type"])

    
    
X = np.array([np.array(Image.open(fname)) for fname in imageList])    
y = np.array(ytrain)



In [30]:
image_vectors = []
for image in X:
    image_vectors.append(image.ravel())
    
image_vectors = np.array(image_vectors)

In [37]:
#Creating the Train/Test Data Split

image_vectors.shape

(2000, 181548)

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(image_vectors,y)
print('Training data and target sizes: \n{}, {}'.format(X_train.shape,y_train.shape))
print('Test data and target sizes: \n{}, {}'.format(X_test.shape,y_test.shape))

Training data and target sizes: 
(1500, 181548), (1500,)
Test data and target sizes: 
(500, 181548), (500,)


In [33]:
from sklearn import svm, metrics

# Create a classifier: a support vector classifier
classifier = svm.SVC(gamma=0.001)
#fit to the trainin data
classifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [34]:
# now to Now predict the value of the digit on the test data
y_pred = classifier.predict(X_test)

In [35]:
print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(y_test, y_pred)))

Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
                precision    recall  f1-score   support

      CurbRamp       0.22      1.00      0.36       109
    NoCurbRamp       0.00      0.00      0.00       124
      Obstacle       0.00      0.00      0.00       132
SurfaceProblem       0.00      0.00      0.00       135

   avg / total       0.05      0.22      0.08       500




/Users/marcus/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [36]:
print("Confusion matrix:\n%s" % metrics.confusion_matrix(y_test, y_pred))

Confusion matrix:
[[109   0   0   0]
 [124   0   0   0]
 [132   0   0   0]
 [135   0   0   0]]


In [29]:
(y == "NoCurbRamp").sum()

501

In [26]:
len(X)

2000