In [13]:
import os
import numpy as np
from PIL import Image
import json


location = "/Users/marcus/Desktop/Training_Data_SVM_Control/"


image_list, json_list = get_image_and_json_paths(location)


    
    
X = color_image_list_to_features(image_list)   
y = json_to_labels(json_list)



In [12]:
def get_image_and_json_paths(file_location):
    image_list = []
    label_list = []
    
    for dirName, x, fileList in os.walk(location):
        for filename in fileList:
            if(filename[-4:] == ".jpg" and not filename[-7:] == "ged.jpg"):

                json_file_location = os.path.join(dirName, filename[:-4] + ".json")

                if os.path.exists(json_file_location):

                    jpg_file_location = os.path.join(dirName, filename)
                    image_list.append(str(jpg_file_location))
                    label_list.append(str(json_file_location))
    
    return image_list, label_list

def json_to_labels(json_path_list):
    y_train = []
    for json_file in json_path_list:
        file = open(json_file)
        data = json.load(file)
        y_train.append(data["Pano_Data"][0]["label_type"])
    
    y_train = np.array(y_train)
    return y_train

def get_image_array(image_list):
    X = np.array([np.array(Image.open(fname)) for fname in image_list])
    return X
    
def color_image_list_to_features(image_list):
    X = get_image_array(image_list) 
    X = X.reshape(X.shape[1]*X.shape[2]*X.shape[3],X.shape[0]).T
    
    return X

In [30]:
image_vectors = []
for image in X:
    image_vectors.append(image.ravel())
    
image_vectors = np.array(image_vectors)

In [37]:
#Creating the Train/Test Data Split

image_vectors.shape

(2000, 181548)

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y)
print('Training data and target sizes: \n{}, {}'.format(X_train.shape,y_train.shape))
print('Test data and target sizes: \n{}, {}'.format(X_test.shape,y_test.shape))

Training data and target sizes: 
(1576, 181548), (1576,)
Test data and target sizes: 
(526, 181548), (526,)


In [15]:
from sklearn import svm, metrics

# Create a classifier: a support vector classifier
classifier = svm.SVC(gamma=0.001)
#fit to the trainin data
classifier.fit(X_train,y_train)

KeyboardInterrupt: 

In [16]:
# now to Now predict the value of the digit on the test data
y_pred = classifier.predict(X_test)

NotFittedError: This SVC instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [35]:
print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(y_test, y_pred)))

Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
                precision    recall  f1-score   support

      CurbRamp       0.22      1.00      0.36       109
    NoCurbRamp       0.00      0.00      0.00       124
      Obstacle       0.00      0.00      0.00       132
SurfaceProblem       0.00      0.00      0.00       135

   avg / total       0.05      0.22      0.08       500




/Users/marcus/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [36]:
print("Confusion matrix:\n%s" % metrics.confusion_matrix(y_test, y_pred))

Confusion matrix:
[[109   0   0   0]
 [124   0   0   0]
 [132   0   0   0]
 [135   0   0   0]]


In [29]:
(y == "NoCurbRamp").sum()

501

In [26]:
len(X)

2000